### ISSUE TITLE
JukeLoop will no longer remember new jukebox locations in the config, therefor not play on restart

### ISSUE THREAD

**Issue by Suffice** [andrepl/JukeLoop#1]
The locations in the config is always empty.

**Comment by andrepl** [comment]
if it's not saving then there should be some message from Jukeloop in the log file when the server is shutting down.  check your logs and paste it here if you find anything.

**Comment by Suffice** [comment]
I get this stacktrace a few times:

```
Line 182835: 2013-03-21 02:05:16 [SEVERE] Error occurred while enabling JukeLoop v0.0.4 (Is it up to date?)
Line 182838:    at com.norcode.bukkit.jukeloop.LoopingJukebox.validate(LoopingJukebox.java:72)
Line 182838:    at com.norcode.bukkit.jukeloop.LoopingJukebox.validate(LoopingJukebox.java:72)
Line 182838:    at com.norcode.bukkit.jukeloop.LoopingJukebox.validate(LoopingJukebox.java:72)
Line 182839:    at com.norcode.bukkit.jukeloop.LoopingJukebox.getAt(LoopingJukebox.java:33)
Line 182839:    at com.norcode.bukkit.jukeloop.LoopingJukebox.getAt(LoopingJukebox.java:33)
Line 182839:    at com.norcode.bukkit.jukeloop.LoopingJukebox.getAt(LoopingJukebox.java:33)
Line 182840:    at com.norcode.bukkit.jukeloop.JukeLoopPlugin.loadData(JukeLoopPlugin.java:106)
Line 182840:    at com.norcode.bukkit.jukeloop.JukeLoopPlugin.loadData(JukeLoopPlugin.java:106)
Line 182840:    at com.norcode.bukkit.jukeloop.JukeLoopPlugin.loadData(JukeLoopPlugin.java:106)
Line 182841:    at com.norcode.bukkit.jukeloop.JukeLoopPlugin.onEnable(JukeLoopPlugin.java:72)
Line 182841:    at com.norcode.bukkit.jukeloop.JukeLoopPlugin.onEnable(JukeLoopPlugin.java:72)
Line 182841:    at com.norcode.bukkit.jukeloop.JukeLoopPlugin.onEnable(JukeLoopPlugin.java:72)
```

**Comment by andrepl** [comment]
There should be more to that stacktrace, it might be helpful.  But from what I can tell there may be a corrupt entry in your config file, can you paste that as well?

**Comment by andrepl** [comment]
also, does each line show up 3x in your log like that? that's really strange...

**Comment by Suffice** [comment]
For a moment there I thought I had two of the plugin running, but checked, and only have one in the plugin directory. Yet I get double enable and disable messages:
    Line 162930: 2013-03-20 03:46:35 [INFO] [JukeLoop] Enabling JukeLoop v0.0.4
    Line 162930: 2013-03-20 03:46:35 [INFO] [JukeLoop] Enabling JukeLoop v0.0.4
    Line 163369: 2013-03-20 04:06:02 [INFO] [JukeLoop] Disabling JukeLoop v0.0.4
    Line 163369: 2013-03-20 04:06:02 [INFO] [JukeLoop] Disabling JukeLoop v0.0.4

The only other thing in the logs is the looping messages.

I haven't tested this with the chest by the jukebox yet, I did not know about that until today.

Everything is double, except for the errors that are triple.

All that's in the config:
jukeboxes: []

**Comment by Suffice** [comment]
My mistake, with the error messages, it turns out it only multiplied because the search on notepad++ gave me the same line multiple times because they had two or three "juke"s per line. That's why the line number is the same.

Here is the full stacktrace:

2013-03-20 02:26:33 [SEVERE] Error occurred while enabling JukeLoop v0.0.4 (Is it up to date?)
java.lang.NullPointerException
    at org.bukkit.Location.getBlock(Location.java:82)
    at com.norcode.bukkit.jukeloop.LoopingJukebox.validate(LoopingJukebox.java:72)
    at com.norcode.bukkit.jukeloop.LoopingJukebox.getAt(LoopingJukebox.java:33)
    at com.norcode.bukkit.jukeloop.JukeLoopPlugin.loadData(JukeLoopPlugin.java:106)
    at com.norcode.bukkit.jukeloop.JukeLoopPlugin.onEnable(JukeLoopPlugin.java:72)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:457)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:381)
    at org.bukkit.craftbukkit.v1_4_R1.CraftServer.loadPlugin(CraftServer.java:282)
    at org.bukkit.craftbukkit.v1_4_R1.CraftServer.enablePlugins(CraftServer.java:264)
    at net.minecraft.server.v1_4_R1.MinecraftServer.j(MinecraftServer.java:321)
    at net.minecraft.server.v1_4_R1.MinecraftServer.e(MinecraftServer.java:300)
    at net.minecraft.server.v1_4_R1.MinecraftServer.a(MinecraftServer.java:259)
    at net.minecraft.server.v1_4_R1.DedicatedServer.init(DedicatedServer.java:149)
    at net.minecraft.server.v1_4_R1.MinecraftServer.run(MinecraftServer.java:399)
    at net.minecraft.server.v1_4_R1.ThreadServerApplication.run(SourceFile:849)

**Comment by andrepl** [comment]
I hate to be difficult, but the stacktrace you pasted can't possibly happen unless there are entries in your config file.  Can you stop the server, then delete and/or rename your server.log and restart it, so that you get a clean and complete log file, then post that somewhere i can review it?

**Comment by Suffice** [comment]
I unloaded the plugin, with PluginManager, deleted the config folder (A while ago, I only deleted the config file), then reloaded and unloaded the plugin, and this time it saved the jukebox location. So whatever it was, it appears to be working now. It doesn't appear to want to save the locations when it is:

jukeboxes: []
Return Space Right Here, Not Sure If It Matters

Thanks for assistance, and creating this great jukebox plugin!

-edit-

Tried it again the way I thought I did it, and it still works.

-edit-

Set the config to how it use to be, and it still ended up working. So I have no idea. The first time I think I added it with Plugin Manager, then restarted, but I don't see why that would matter, unless it didn't save on restart for some reason. I won't test that right now, but I'll try to get back to you about it later.

**Comment by Suffice** [comment]
Still works, for whatever the reason.

**Comment by Suffice** [comment]
It happened again! I noticed that it stopped playing, and then I reloaded the plugin, and found this in the config: 

jukeboxes: []

So it might be removing jukebox locations once in a while. .?

**Comment by andrepl** [comment]
It's quite possible the plugin just doesn't handle /reload very well.  I'll do some testing with that when I have a chance.

**Comment by andrepl** [comment]
I wasn't able to reproduce it, but I am running a slightly newer version of jukeloop thats not on dev.bukkit.org yet. (still a few bugs to work out)  do you /reload your server often? I've found it causes problems with a lot of plugins so I never do it.  surprisingly though, it's not causing any problems for me with jukeloop.  I'll put some time into 0.0.5 tonight and try to release it for testing.

**Comment by Suffice** [comment]
/reload is less buggy than it use to be, but that wasn't what I was using. I was using Plugin Manager, which is better for individual plugins. I'm pretty sure it is not to do with reloading. I'll see if I can get the location jukebox to stop playing and disappear again.

Could it be the player location and amount of players on?

**Comment by andrepl** [comment]
if  you are far away, but there are other players near the jukebox when it switches songs, when you return, you wont hear the currently playing song. that's something built into minecraft that I can't work around without weird hacks that will put the music WAY out of sync for other players.  

There's no reason it would be removed from the config file though unless the jukebox is destroyed.

**Comment by andrepl** [comment]
0.1.0 is going to be ready soon, its got HOPPER Support!

**Comment by andrepl** [comment]
I uploaded 0.1.0 to dev.bukkit.org so I'm going to close this issue for now, if the problem happens again with the new release open a new issue.
