### ISSUE TITLE
Jukebox music is quieter

### ISSUE THREAD

**Issue by Bromine** [andrepl/JukeLoop#10]
This plugin works perfectly, it sounds fine when you first place the disk in, but when you change the song, it will sound significantly quieter than the previous one, and it seems that it remains at this volume as it cycles though the songs. I also discovered that when you just click on your Music Volume bar, the sound returns to the level that it should have been at. I've been using this plugin on a server with my friends and they have all noticed the same thing.
Of course this isn't a ridiculously horrible issue, but it is annoying to not be able to hear the music very well. Thanks for reading and stuff.

**Comment by andrepl** [comment]
Strange, I've been running it for a LONG time on my server and never noticed, or heard this complaint before.  I'll do some testing and see if I can figure it out.

**Comment by Bromine** [comment]
I'm uploading a video on YouTube so you can actually hear what's going on. http://www.youtube.com/watch?v=r-Ihkcl9i3E&feature=youtu.be

**Comment by andrepl** [comment]
This happens WITHOUT JukeLoop too, its a vanilla minecraft issue.
