### ISSUE TITLE
Adding non-vanilla Discs

### ISSUE THREAD

**Issue by Mahribar** [andrepl/JukeLoop#11]
Hey,

is there any way to add a possibility in the config, that we can add non-vanilla discs like the ones of the portal-gun-mod to your awesome plugin?

Greets, 
Mahribar.

**Comment by andrepl** [comment]
Thanks for creating the ticket, I completely forgot about this feature request!  Check back in an hour or so.

**Comment by andrepl** [comment]
There's a dev build [here](http://ci.minevsmine.com/job/JukeLoop/4/). I haven't actually tried it as I've never run any modded servers before, but it should be as simple as adding the ID or Material name (not sure if modded blocks have those) to the list in config.yml along with the correct duration of the song in seconds.

**Comment by Mahribar** [comment]
Good Morning,

I´ve tested the new version by adding the Item-ID´s in the config, but everytime when i restart the server, to apply the changes, the config is overwritten by the standard one. :(
So I can´t really test the new version ^^

So long,
Mahribar

**Comment by andrepl** [comment]
you cannot edit the config file while the server is running, shut it down, make your changes, and then start it again. it won't get overwritten that way

**Comment by Mahribar** [comment]
Ups, my Mistake ^^
Tested again and it´s working! Good job and thanks a lot!

So long,
Mahribar

**Comment by andrepl** [comment]
Glad it's working, I'll publish this version to bukkitdev today.
