### ISSUE TITLE
Console spam

### ISSUE THREAD

**Issue by liquidox** [andrepl/JukeLoop#2]
I think you left some debug behind:

15:24:33 [INFO] [JukeLoop] Checking EAST
15:24:33 [INFO] [JukeLoop] Checking WEST
15:24:33 [INFO] [JukeLoop] Checking NORTH
15:24:33 [INFO] [JukeLoop] Checking SOUTH
15:24:33 [INFO] [JukeLoop] Checking UP
15:24:34 [INFO] [JukeLoop] Checking EAST
15:24:34 [INFO] [JukeLoop] Checking WEST
15:24:34 [INFO] [JukeLoop] Checking NORTH
15:24:34 [INFO] [JukeLoop] Checking SOUTH
15:24:34 [INFO] [JukeLoop] Checking UP
15:24:36 [INFO] [JukeLoop] Checking EAST
15:24:36 [INFO] [JukeLoop] Checking WEST
15:24:36 [INFO] [JukeLoop] Checking NORTH
15:24:36 [INFO] [JukeLoop] Checking SOUTH
15:24:36 [INFO] [JukeLoop] Checking UP

**Comment by andrepl** [comment]
Oh wow, thanks.  I removed it and will re-upload to dev.bukkit.org right now. in the meantime you can download a temporary fixed build here. https://www.box.com/s/e0px3c4265leajne3wwl
