### ISSUE TITLE
Error on restart

### ISSUE THREAD

**Issue by liquidox** [andrepl/JukeLoop#4]
http://pastie.org/pastes/7171382/text?key=cc3nvv6znwexcrohswujdw

**Comment by andrepl** [comment]
Interesting that this never got reported earlier, this is a complete incompatibility with any world with an _ in the name... Its fixed as of 0.1.2, downloadable here: https://www.box.com/s/e0px3c4265leajne3wwl until its approved on dev.bukkit.org

This one also has some optional debugging if you specify debug: true in the config, but its fairly spammy, so I dont recommend enabling it on a live server.
