### ISSUE TITLE
Error occurred while enabling JukeLoop v0.1.2

### ISSUE THREAD

**Issue by liquidox** [andrepl/JukeLoop#5]
Still bugs:

http://pastie.org/pastes/7189035/text?key=ibdwt55ajchgzlggxajmga

**Comment by andrepl** [comment]
can you try this development build: https://www.box.com/s/5direjri2rkn26rzq4lg

it should print a [WARNING] line and then continue normally, but I'd like to see that warning, I can't seem to reproduce the error, and it sounds like maybe the chunk containing that jukebox was deleted from the world?

**Comment by andrepl** [comment]
This should be fixed by 0.1.3
