### ISSUE TITLE
Activate on....

### ISSUE THREAD

**Issue by Rickious** [andrepl/JukeLoop#6]
Any way you can add the missing features to activate jukeboxes on redstone/pressureplate/switch etc?  This is an obvious abilitly missing from MC and would be great if you could add it to your plugin.

**Comment by andrepl** [comment]
This has been requested a few times before.  I've never done any redstone-related code before so It'll take some time to figure out but I'll add it to my list of things to do.

**Comment by andrepl** [comment]
Did it! 0.1.4 has support for redstone triggering.

**Comment by Rickious** [comment]
Excellent! :+1:
