### ISSUE TITLE
Still broken

### ISSUE THREAD

**Issue by liquidox** [andrepl/JukeLoop#7]
New version still errors on loading, new error this time:

http://pastie.org/pastes/7325830/text?key=zaiobklvddselbrky7gja

**Comment by andrepl** [comment]
as far as I can tell that's harmless, just spammy.  Its removed in the latest builds, along with a new redstone feature.  you can grab a dev build here, or I'll be pushing to dev.bukkit.org soon.

http://mcgitlab.norcode.com:8081/job/JukeLoop/4/JukeLoop$JukeLoop/

**Comment by liquidox** [comment]
Nope, invalid plugin.yml file in that dev version, wont load.

**Comment by andrepl** [comment]
Ah, sorry I suck at maven. :) next build has it.

**Comment by liquidox** [comment]
Seems ok.
